active_strategy: Moving_Average_Crossover
commission_rate: 0.001
end_date: '2025-06-30'
initial_capital: 10000.0
start_date: '2025-01-01'
strategy_parameters:
  Moving_Average_Crossover:
    long_window: 30
    short_window: 10
tickers:
- BTCUSD
timeframe: 1h
